-- Seed 50 well-known Japanese school choir works.
-- Provisional metadata; editions are marked unverified.
BEGIN TRANSACTION;
CREATE TEMP TABLE seed_songs (id TEXT, title TEXT, title_kana TEXT, lyricist TEXT, composer TEXT, voicing TEXT, accompaniment TEXT, difficulty INTEGER);
INSERT INTO seed_songs VALUES
  ('cosmos', 'COSMOS', 'こすもす', 'ミマス', 'ミマス', '混声三部', 'ピアノ', 3),
  ('taisetsu-na-mono', '大切なもの', 'たいせつなもの', '山崎朋子', '山崎朋子', '混声三部', 'ピアノ', 2),
  ('tabidachi-no-hi-ni', '旅立ちの日に', 'たびだちのひに', '小嶋登', '坂本浩美', '混声三部', 'ピアノ', 2),
  ('believe', 'Believe', 'びりーぶ', '杉本竜一', '杉本竜一', '混声三部', 'ピアノ', 2),
  ('anata-e', 'あなたへ―旅立ちに寄せるメッセージ', 'あなたへ', '筒井雅子', '筒井雅子', '混声三部', 'ピアノ', 3),
  ('heiwa-no-kane', 'HEIWAの鐘', 'へいわのかね', '仲里幸広', '仲里幸広', '混声三部', 'ピアノ', 3),
  ('toki-no-tabibito', '時の旅人', 'ときのたびびと', '深田じゅんこ', '橋本祥路', '混声三部', 'ピアノ', 3),
  ('lets-search-for-tomorrow', 'Let''s Search for Tomorrow', 'れっつさーちふぉーとぅもろー', '堀徹', '大澤徹訓', '混声三部', 'ピアノ', 3),
  ('kokoro-no-hitomi', '心の瞳', 'こころのひとみ', '荒木とよひさ', '三木たかし', '混声三部', 'ピアノ', 3),
  ('my-ballad', 'マイ バラード', 'まいばらーど', '松井孝夫', '松井孝夫', '混声三部', 'ピアノ', 2),
  ('kaiju-no-ballad', '怪獣のバラード', 'かいじゅうのばらーど', '岡田冨美子', '東海林修', '混声三部', 'ピアノ', 2),
  ('tsubasa-wo-kudasai', '翼をください', 'つばさをください', '山上路夫', '村井邦彦', '混声三部', 'ピアノ', 2),
  ('yume-no-sekai-wo', '夢の世界を', 'ゆめのせかいを', '芙龍明子', '橋本祥路', '混声三部', 'ピアノ', 2),
  ('kono-hoshi-ni-umarete', 'この星に生まれて', 'このほしにうまれて', '杉本竜一', '杉本竜一', '混声三部', 'ピアノ', 2),
  ('chikyuu-seika', '地球星歌～笑顔のために～', 'ちきゅうせいか', 'ミマス', 'ミマス', '混声三部', 'ピアノ', 3),
  ('kizuna', '絆', 'きずな', '山崎朋子', '山崎朋子', '混声三部', 'ピアノ', 2),
  ('niji', '虹', 'にじ', '森山直太朗・御徒町凧', '森山直太朗・御徒町凧', '混声三部', 'ピアノ', 3),
  ('shinjiru', '信じる', 'しんじる', '谷川俊太郎', '松下耕', '混声三部', 'ピアノ', 4),
  ('kikoeru', '聞こえる', 'きこえる', '岩間芳樹', '新実徳英', '混声四部', 'ピアノ', 4),
  ('haru-ni', '春に', 'はるに', '谷川俊太郎', '木下牧子', '混声三部', 'ピアノ', 4),
  ('sono-hito-ga-utau-toki', 'そのひとがうたうとき', 'そのひとがうたうとき', '谷川俊太郎', '木下牧子', '混声四部', 'ピアノ', 4),
  ('nijuuoku-kounen-no-kodoku', '二十億光年の孤独', 'にじゅうおくこうねんのこどく', '谷川俊太郎', '木下牧子', '混声四部', 'ピアノ', 4),
  ('hajimari', 'はじまり', 'はじまり', '工藤直子', '木下牧子', '混声四部', 'ピアノ', 4),
  ('nazukerareta-ha', '名づけられた葉', 'なづけられたは', '新川和江', '加賀清孝', '混声三部', 'ピアノ', 3),
  ('yokan', '予感', 'よかん', '片岡輝', '大熊崇子', '混声三部', 'ピアノ', 4),
  ('aoba-no-uta', '青葉の歌', 'あおばのうた', '小森香子', '熊谷賢一', '混声三部', 'ピアノ', 3),
  ('daichi-sanshou', '大地讃頌', 'だいちさんしょう', '大木惇夫', '佐藤眞', '混声四部', 'ピアノ', 4),
  ('kakou', '河口', 'かこう', '丸山豊', '團伊玖磨', '混声四部', 'ピアノ', 5),
  ('oyashirazu-koshirazu', '親知らず子知らず', 'おやしらずこしらず', '山本和夫', '岩河三郎', '混声四部', 'ピアノ', 4),
  ('kieta-hachigatsu', '消えた八月', 'きえたはちがつ', '栄谷温子', '黒沢吉徳', '混声三部', 'ピアノ', 4),
  ('mokkin', '木琴', 'もっきん', '金井直', '岩河三郎', '混声四部', 'ピアノ', 4),
  ('hitotsu-no-asa', 'ひとつの朝', 'ひとつのあさ', '片岡輝', '平吉毅州', '混声三部', 'ピアノ', 4),
  ('hashiru-kawa', '走る川', 'はしるかわ', '金沢智恵子', '黒沢吉徳', '混声四部', 'ピアノ', 4),
  ('sasurai-no-tami', '流浪の民', 'るろうのたみ', '石倉小三郎（訳詞）', 'ロベルト・シューマン', '混声四部', 'ピアノ', 5),
  ('moldau', 'モルダウ', 'もるだう', '岩河三郎（日本語詞・編曲）', 'ベドルジハ・スメタナ', '混声三部', 'ピアノ', 4),
  ('sora-kakeru-tenma', '空駆ける天馬', 'そらかけるてんま', '館蓬莱', '黒沢吉徳', '混声三部', 'ピアノ', 4),
  ('tooi-hi-no-uta', '遠い日の歌', 'とおいひのうた', '岩沢千早', '橋本祥路', '混声三部', 'ピアノ', 3),
  ('namida-wo-koete', '涙をこえて', 'なみだをこえて', 'かぜ耕士', '中村八大', '混声三部', 'ピアノ', 2),
  ('ashita-e', '明日へ', 'あしたへ', '富岡博志', '富岡博志', '混声三部', 'ピアノ', 3),
  ('with-you-smile', 'With You Smile', 'うぃずゆーすまいる', '水本誠', '水本誠', '混声三部', 'ピアノ', 2),
  ('kimi-to-mita-umi', '君とみた海', 'きみとみたうみ', '若松歓', '若松歓', '混声三部', 'ピアノ', 3),
  ('mirai-e', '未来へ', 'みらいへ', '玉城千春', '玉城千春', '混声三部', 'ピアノ', 2),
  ('gunjou', '群青', 'ぐんじょう', '福島県南相馬市立小高中学校平成24年度卒業生', '小田美樹', '混声三部', 'ピアノ', 3),
  ('akashi', '証', 'あかし', '山村隆太', '阪井一生', '混声三部', 'ピアノ', 3),
  ('yell', 'YELL', 'えーる', '水野良樹', '水野良樹', '混声三部', 'ピアノ', 3),
  ('tegami', '手紙 ～拝啓 十五の君へ～', 'てがみ', 'アンジェラ・アキ', 'アンジェラ・アキ', '混声三部', 'ピアノ', 3),
  ('furusato-arashi', 'ふるさと', 'ふるさと', '小山薫堂', 'youth case', '混声三部', 'ピアノ', 3),
  ('tomo-tabidachi-no-toki', '友 ～旅立ちの時～', 'ともたびだちのとき', '北川悠仁', '北川悠仁', '混声三部', 'ピアノ', 3),
  ('sakura-no-ame', '桜ノ雨', 'さくらのあめ', 'halyosy', 'halyosy', '混声三部', 'ピアノ', 3),
  ('kawaranai-mono', '変わらないもの', 'かわらないもの', '山崎朋子', '山崎朋子', '混声三部', 'ピアノ', 3);
INSERT OR IGNORE INTO works (id,title,title_kana,lyricist,composer,published) SELECT id,title,title_kana,lyricist,composer,1 FROM seed_songs;
INSERT INTO editions (work_id,voicing,accompaniment,difficulty,verification_status) SELECT s.id,s.voicing,s.accompaniment,s.difficulty,'unverified' FROM seed_songs s WHERE NOT EXISTS (SELECT 1 FROM editions e WHERE e.work_id=s.id AND e.voicing=s.voicing AND e.accompaniment=s.accompaniment);
DROP TABLE seed_songs;
COMMIT;